export const SIDEBAR = {
	SIDEBAR_SET: "SIDEBAR_SET",
}

export const LOADING = {
	LOADING: "LOADING",
	SUCCESS: "LOADING_SUCCESS",
	FAILURE: "LOADING_FAILURE",
	CLEAR: "LOADING_CLEAR",
}

export const ALERT = {
	SUCCESS: "ALERT_SUCCESS",
	ERROR: "ALERT_ERROR",
	NOTIFY: "ALERT_NOTIFY",
	INFO: "ALERT_INFO",
	CLEAR: "ALERT_CLEAR",
}
